//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class informazia
    {
        public int id { get; set; }
        public string familia { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public Nullable<int> vosrast { get; set; }
    }
}
